#!/bin/sh

CACHES_DIR=/var/cache/oresat_linux_manager
CONF_FILE=/etc/oresat-linux-manager.conf

if [ $1 = "purge" ]; then
    rm -rf $CACHES_DIR
    rm -rf $CONF_FILE
fi

systemctl daemon-reload

exit 0
